// Code generated by MockGen. DO NOT EDIT.
// Source: gh/gh.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	target "github.com/k1LoW/ghdag/target"
)

// MockGhClient is a mock of GhClient interface.
type MockGhClient struct {
	ctrl     *gomock.Controller
	recorder *MockGhClientMockRecorder
}

// MockGhClientMockRecorder is the mock recorder for MockGhClient.
type MockGhClientMockRecorder struct {
	mock *MockGhClient
}

// NewMockGhClient creates a new mock instance.
func NewMockGhClient(ctrl *gomock.Controller) *MockGhClient {
	mock := &MockGhClient{ctrl: ctrl}
	mock.recorder = &MockGhClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGhClient) EXPECT() *MockGhClientMockRecorder {
	return m.recorder
}

// AddComment mocks base method.
func (m *MockGhClient) AddComment(ctx context.Context, n int, comment string, mentions []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddComment", ctx, n, comment, mentions)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddComment indicates an expected call of AddComment.
func (mr *MockGhClientMockRecorder) AddComment(ctx, n, comment, mentions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddComment", reflect.TypeOf((*MockGhClient)(nil).AddComment), ctx, n, comment, mentions)
}

// CloseIssue mocks base method.
func (m *MockGhClient) CloseIssue(ctx context.Context, n int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIssue", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseIssue indicates an expected call of CloseIssue.
func (mr *MockGhClientMockRecorder) CloseIssue(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIssue", reflect.TypeOf((*MockGhClient)(nil).CloseIssue), ctx, n)
}

// FetchTarget mocks base method.
func (m *MockGhClient) FetchTarget(ctx context.Context, n int) (*target.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTarget", ctx, n)
	ret0, _ := ret[0].(*target.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTarget indicates an expected call of FetchTarget.
func (mr *MockGhClientMockRecorder) FetchTarget(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTarget", reflect.TypeOf((*MockGhClient)(nil).FetchTarget), ctx, n)
}

// FetchTargets mocks base method.
func (m *MockGhClient) FetchTargets(ctx context.Context) (target.Targets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTargets", ctx)
	ret0, _ := ret[0].(target.Targets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTargets indicates an expected call of FetchTargets.
func (mr *MockGhClientMockRecorder) FetchTargets(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTargets", reflect.TypeOf((*MockGhClient)(nil).FetchTargets), ctx)
}

// MergePullRequest mocks base method.
func (m *MockGhClient) MergePullRequest(ctx context.Context, n int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePullRequest", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// MergePullRequest indicates an expected call of MergePullRequest.
func (mr *MockGhClientMockRecorder) MergePullRequest(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePullRequest", reflect.TypeOf((*MockGhClient)(nil).MergePullRequest), ctx, n)
}

// ResolveUsers mocks base method.
func (m *MockGhClient) ResolveUsers(ctx context.Context, in []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUsers", ctx, in)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUsers indicates an expected call of ResolveUsers.
func (mr *MockGhClientMockRecorder) ResolveUsers(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUsers", reflect.TypeOf((*MockGhClient)(nil).ResolveUsers), ctx, in)
}

// SetAssignees mocks base method.
func (m *MockGhClient) SetAssignees(ctx context.Context, n int, assignees []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAssignees", ctx, n, assignees)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAssignees indicates an expected call of SetAssignees.
func (mr *MockGhClientMockRecorder) SetAssignees(ctx, n, assignees interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAssignees", reflect.TypeOf((*MockGhClient)(nil).SetAssignees), ctx, n, assignees)
}

// SetLabels mocks base method.
func (m *MockGhClient) SetLabels(ctx context.Context, n int, labels []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabels", ctx, n, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLabels indicates an expected call of SetLabels.
func (mr *MockGhClientMockRecorder) SetLabels(ctx, n, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabels", reflect.TypeOf((*MockGhClient)(nil).SetLabels), ctx, n, labels)
}

// SetReviewers mocks base method.
func (m *MockGhClient) SetReviewers(ctx context.Context, n int, reviewers []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReviewers", ctx, n, reviewers)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReviewers indicates an expected call of SetReviewers.
func (mr *MockGhClientMockRecorder) SetReviewers(ctx, n, reviewers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReviewers", reflect.TypeOf((*MockGhClient)(nil).SetReviewers), ctx, n, reviewers)
}
