name: ghdag workflow
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  run-workflow:
    name: Run workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ghdag
        run: |
          cat $GITHUB_EVENT_PATH
          make build
          ./ghdag run .ghdag.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
